Civil-Service-Human-Resources/lpg-learner-record

- src/main/java/uk/gov/cslearning/record/service/scheduler/Scheduler.java
- scheduler was set to run every min, hence we were getting lots of logs
- fixing this to run every day at 2am
> fixing scheduler cron

- Jenkinsfile
> complete jenkinsfile

- src/main/java/uk/gov/cslearning/record/api/BookingController.java
- src/main/java/uk/gov/cslearning/record/domain/Booking.java
- src/main/java/uk/gov/cslearning/record/dto/BookingStatusDto.java
- src/main/java/uk/gov/cslearning/record/exception/BookingNotFoundException.java
- src/main/java/uk/gov/cslearning/record/service/BookingService.java
- src/main/java/uk/gov/cslearning/record/service/DefaultBookingService.java
- src/main/java/uk/gov/cslearning/record/validation/annotations/BookingStatusEquals.java
- src/main/java/uk/gov/cslearning/record/validation/validators/BookingStatusEqualsValidator.java
- src/main/resources/ValidationMessages.properties
- src/test/java/uk/gov/cslearning/record/api/BookingControllerTest.java
- src/test/java/uk/gov/cslearning/record/service/DefaultBookingServiceTest.java
- src/test/java/uk/gov/cslearning/record/validation/validators/BookingStatusEqualsValidatorTest.java
Created PATCH endpoint to update booking status.
> LPFG-944: Create an endpoint to update booking status

- src/main/java/uk/gov/cslearning/record/api/BookingController.java
- src/main/java/uk/gov/cslearning/record/domain/factory/BookingFactory.java
- src/main/java/uk/gov/cslearning/record/dto/BookingDto.java
- src/main/java/uk/gov/cslearning/record/dto/factory/BookingDtoFactory.java
- src/main/java/uk/gov/cslearning/record/exception/BookingNotFoundException.java
- src/main/java/uk/gov/cslearning/record/repository/BookingRepository.java
- src/main/java/uk/gov/cslearning/record/repository/CourseRecordRepository.java
- src/main/java/uk/gov/cslearning/record/service/BookingService.java
- src/main/java/uk/gov/cslearning/record/service/DefaultBookingService.java
- src/main/java/uk/gov/cslearning/record/service/xapi/XApiService.java
- src/main/java/uk/gov/cslearning/record/service/xapi/factory/ContextFactory.java
- src/main/java/uk/gov/cslearning/record/service/xapi/factory/StatementFactory.java
- src/main/resources/db/migration/mysql/V1.1.5__add-event-learner-booking-tables.sql
- src/test/java/uk/gov/cslearning/record/api/BookingControllerTest.java
- src/test/java/uk/gov/cslearning/record/domain/factory/BookingFactoryTest.java
- src/test/java/uk/gov/cslearning/record/dto/factory/BookingDtoFactoryTest.java
- src/test/java/uk/gov/cslearning/record/repository/BookingRepositoryTest.java
- src/test/java/uk/gov/cslearning/record/service/DefaultBookingServiceTest.java
- src/test/java/uk/gov/cslearning/record/service/xapi/factory/ContextFactoryTest.java
- src/test/java/uk/gov/cslearning/record/service/xapi/factory/StatementFactoryTest.java
- Added extra PATCH endpoint to allow cancellaton of event by user in UI.
- Added course and module ids to statements posted to XAPI.
> LPFG-989: Update Learner UI to register learner

- src/main/java/uk/gov/cslearning/record/api/EventController.java
- src/main/java/uk/gov/cslearning/record/csrs/service/RegistryService.java
- src/main/java/uk/gov/cslearning/record/dto/CancellationReason.java
- src/main/java/uk/gov/cslearning/record/service/DefaultEventService.java
- src/test/java/uk/gov/cslearning/record/service/DefaultEventServiceTest.java
Added getCancellationReason endpoint to EventController.java
Added full reason values to CancellationReason.java
Set cancellation reason directly from value in DefaultEventService.java
> LPFG-1189-cancellation-reason-enums

- src/main/java/uk/gov/cslearning/record/api/BookingController.java
- src/main/java/uk/gov/cslearning/record/csrs/service/RegistryService.java
- src/main/java/uk/gov/cslearning/record/service/BookingService.java
- src/main/java/uk/gov/cslearning/record/service/DefaultBookingService.java
- src/test/java/uk/gov/cslearning/record/api/BookingControllerTest.java
- src/test/java/uk/gov/cslearning/record/service/DefaultBookingServiceTest.java
This adds a 'getActiveBooking' endpoint, which returns a booking if active for a learnerUid and eventUid. This is used to check if a learner is booked onto an event.
- Added getActiveBooking endpoint to **BookingController.java**
- Added findByLearnerUidAndEventUid function to **DefaultBookingService.java**
> Lpfg 1262 reapeat booking journey

- src/main/resources/application.yml
> LC-154: updating caffine config in yml

- src/main/java/uk/gov/cslearning/record/domain/BookingStatus.java
- src/main/java/uk/gov/cslearning/record/repository/BookingRepository.java
- src/main/java/uk/gov/cslearning/record/service/BookingService.java
- src/main/java/uk/gov/cslearning/record/service/DefaultBookingService.java
- src/main/java/uk/gov/cslearning/record/service/DefaultInviteService.java
- src/main/java/uk/gov/cslearning/record/service/UserRecordService.java
- src/main/java/uk/gov/cslearning/record/service/xapi/action/RegisteredAction.java
- src/test/java/uk/gov/cslearning/record/dto/factory/LearnerRecordEventFactoryTest.java
- src/test/java/uk/gov/cslearning/record/service/DefaultBookingServiceTest.java
- src/test/java/uk/gov/cslearning/record/service/UserRecordServiceTest.java
- fix to get status of booking from booking table not xapi
> LC-139: status of booking

- src/main/java/uk/gov/cslearning/record/service/DefaultBookingService.java
- src/main/java/uk/gov/cslearning/record/service/UserRecordService.java
- src/main/java/uk/gov/cslearning/record/service/xapi/Verb.java
- src/main/java/uk/gov/cslearning/record/service/xapi/XApiService.java
- src/main/java/uk/gov/cslearning/record/service/xapi/action/ApprovedAction.java
- src/main/java/uk/gov/cslearning/record/service/xapi/factory/StatementFactory.java
- src/main/java/uk/gov/cslearning/record/service/xapi/factory/VerbFactory.java
- src/test/java/uk/gov/cslearning/record/service/DefaultBookingServiceTest.java
- updating event status xapi statements
> LC-139-status-v2

- src/main/java/uk/gov/cslearning/record/domain/ModuleRecord.java
- src/main/java/uk/gov/cslearning/record/dto/factory/ModuleRecordDtoFactory.java
- src/main/java/uk/gov/cslearning/record/repository/ModuleRecordRepository.java
- src/main/java/uk/gov/cslearning/record/service/ModuleRecordService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/cslearning/record/repository/ModuleRecordRepositoryTest.java
- src/test/java/uk/gov/cslearning/record/service/ModuleRecordServiceTest.java
> LC-180: adding ignore for non-related data

- src/main/java/uk/gov/cslearning/record/dto/ModuleRecordDto.java
- src/main/java/uk/gov/cslearning/record/repository/ModuleRecordRepository.java
- src/main/java/uk/gov/cslearning/record/service/ModuleRecordService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/cslearning/record/repository/ModuleRecordRepositoryTest.java
- src/test/java/uk/gov/cslearning/record/service/ModuleRecordServiceTest.java
- custom query to improve reporting performance
> LC-221-module-record-performance

- src/main/java/uk/gov/cslearning/record/dto/ModuleRecordDto.java
- src/main/java/uk/gov/cslearning/record/repository/ModuleRecordRepository.java
- src/test/java/uk/gov/cslearning/record/repository/ModuleRecordRepositoryTest.java
- adding updated/completed date columns
> Lc 221 updated completed dates

- src/test/java/uk/gov/cslearning/record/api/LearnerControllerTest.java
> fix-thread-testing-fix

- src/main/java/uk/gov/cslearning/record/api/LearnerController.java
- src/main/java/uk/gov/cslearning/record/config/MongoConfig.java
- src/main/java/uk/gov/cslearning/record/config/MongoProperties.java
- src/main/java/uk/gov/cslearning/record/service/DefaultLearnerService.java
- src/main/java/uk/gov/cslearning/record/service/scheduler/Scheduler.java
- src/main/resources/application.yml
> fix-removing-threading

- src/main/java/uk/gov/cslearning/record/service/RequestEntityFactory.java
- updating auth on scheduler to run using client creds
> fix-scheduler-auth-fix

- src/main/java/uk/gov/cslearning/record/config/OAuthProperties.java
- src/main/java/uk/gov/cslearning/record/config/SecurityConfig.java
- src/main/resources/application.yml
Added "PoolingHttpClientConnectionManager" to be used by OAuth2RestTemplate in order to increase its efficiency. The manager is also configurable.
> Implemented PoolingHttpClientConnectionManager to be used for requests

- src/main/resources/db/migration/h2/V1.4.0__add_index_to_module_record.sql
- src/main/resources/db/migration/mysql/V1.4.0__add_index_to_module_record.sql
Added index for module record to be sorted by descending order of  'updated_at' column.
> Adding index for module record

- src/main/resources/db/migration/h2/V1.4.0__add_index_to_module_record.sql
- src/main/resources/db/migration/mysql/V1.4.0__add_index_to_module_record.sql
Reverts Civil-Service-Human-Resources/lpg-learner-record#106
Removing from master until scheduled release, will recreate PR for a release branch for now
> Revert "Adding index for module record"

- build.gradle
- src/main/java/uk/gov/cslearning/record/api/BookingController.java
- src/main/java/uk/gov/cslearning/record/csrs/service/RegistryService.java
- src/main/java/uk/gov/cslearning/record/domain/Booking.java
- src/main/java/uk/gov/cslearning/record/domain/factory/BookingFactory.java
- src/main/java/uk/gov/cslearning/record/dto/BookingDto.java
- src/main/java/uk/gov/cslearning/record/dto/factory/BookingDtoFactory.java
- src/main/java/uk/gov/cslearning/record/exception/CivilServantNotFoundException.java
- src/main/java/uk/gov/cslearning/record/service/BookingService.java
- src/main/java/uk/gov/cslearning/record/service/DefaultBookingService.java
- src/main/java/uk/gov/cslearning/record/service/MessageService.java
- src/main/java/uk/gov/cslearning/record/service/booking/BookingNotificationService.java
- src/main/resources/application.yml
- src/main/resources/db/migration/h2/V1.3.1__add_booking_reference_to_booking.sql
- src/main/resources/db/migration/mysql/V1.3.1__add_booking_reference_to_booking.sql
- src/test/java/uk/gov/cslearning/record/csrs/service/RegistryServiceTest.java
- src/test/java/uk/gov/cslearning/record/service/DefaultBookingServiceTest.java
- src/test/java/uk/gov/cslearning/record/service/MessageServiceTest.java
- src/test/java/uk/gov/cslearning/record/service/booking/BookingNotificationServiceTest.java
**Jira Ticket:** 
https://cshrdigitalandanalysis.atlassian.net/browse/LC-280
This branch adds booking reference to the course which is used by the other apis as explained bellow: 
1. Added booking reference to the learner email for the 3 different scenarios of an event (request, confirm, cancellation)
Done in this branch 
2. Added booking reference to the line manager email for the 3 different scenarios of an event getting booked by a learner (request, confirm, cancellation) 
Done in this branch 
3. Added booking reference to the MI report. 
https://github.com/Civil-Service-Human-Resources/lpg-report-service/pull/26
4. Added to the event overview in the Admin page. 
https://github.com/Civil-Service-Human-Resources/lpg-management/pull/233
> Feature lc 280 adding booking reference

- build.gradle
- src/main/java/uk/gov/cslearning/record/api/BookingController.java
- src/main/java/uk/gov/cslearning/record/csrs/service/RegistryService.java
- src/main/java/uk/gov/cslearning/record/domain/Booking.java
- src/main/java/uk/gov/cslearning/record/domain/factory/BookingFactory.java
- src/main/java/uk/gov/cslearning/record/dto/BookingDto.java
- src/main/java/uk/gov/cslearning/record/dto/factory/BookingDtoFactory.java
- src/main/java/uk/gov/cslearning/record/exception/CivilServantNotFoundException.java
- src/main/java/uk/gov/cslearning/record/service/BookingService.java
- src/main/java/uk/gov/cslearning/record/service/DefaultBookingService.java
- src/main/java/uk/gov/cslearning/record/service/MessageService.java
- src/main/java/uk/gov/cslearning/record/service/booking/BookingNotificationService.java
- src/main/resources/application.yml
- src/main/resources/db/migration/h2/V1.3.1__add_booking_reference_to_booking.sql
- src/main/resources/db/migration/mysql/V1.3.1__add_booking_reference_to_booking.sql
- src/test/java/uk/gov/cslearning/record/csrs/service/RegistryServiceTest.java
- src/test/java/uk/gov/cslearning/record/service/DefaultBookingServiceTest.java
- src/test/java/uk/gov/cslearning/record/service/MessageServiceTest.java
- src/test/java/uk/gov/cslearning/record/service/booking/BookingNotificationServiceTest.java
_WIP until all feature branches are merged_
Contains the following PRs:
https://github.com/Civil-Service-Human-Resources/lpg-learner-record/pull/107
> [WIP] Releases - F2F features

- src/main/java/uk/gov/cslearning/record/service/MessageService.java
Avoid dotting on nulls. Introduced a bit of guarding in stream ops.
> Hotfix null accessors

- src/main/java/uk/gov/cslearning/record/config/OAuthProperties.java
- src/main/java/uk/gov/cslearning/record/config/SecurityConfig.java
- src/main/resources/application.yml
> Release performance release e2

- .gitignore
- src/main/java/uk/gov/cslearning/record/service/scheduler/Scheduler.java
- src/main/resources/application.yml
Sending this PR as an option - let's chat about how we'd extract the schedule to env vars (would need paired with a change in lpg-terraform-paas repo to set the vars per-env)
> Adding option for scheduled job crons set by env var

- src/main/java/uk/gov/cslearning/record/service/CourseRefreshService.java
- src/main/java/uk/gov/cslearning/record/service/NotifyService.java
- src/main/java/uk/gov/cslearning/record/service/scheduler/LearningJob.java
- src/main/java/uk/gov/cslearning/record/service/xapi/XApiService.java
Extra logging for debugging notifications.
> LC 654 extra logging for notifications

- src/main/java/uk/gov/cslearning/record/csrs/service/RegistryService.java
- src/main/java/uk/gov/cslearning/record/service/xapi/StatementStream.java
- src/main/resources/application.yml
- src/test/java/uk/gov/cslearning/record/csrs/service/RegistryServiceTest.java
We fetch organisation with parents from civil servants registry for extra check.
> Implemented extra organisation check

- src/main/java/uk/gov/cslearning/record/api/input/POST/PostModuleRecordInput.java
- src/main/java/uk/gov/cslearning/record/domain/ModuleRecord.java
- src/main/java/uk/gov/cslearning/record/dto/ModuleRecordDto.java
- src/main/java/uk/gov/cslearning/record/repository/ModuleRecordRepository.java
- src/main/java/uk/gov/cslearning/record/service/ModuleRecordService.java
- src/main/resources/db/migration/h2/V1.6.0__add_uniqueness_module_record_user_id_module_id.sql
- src/main/resources/db/migration/h2/V1.7.0__add-uid-column-in-module-record.sql
- src/main/resources/db/migration/mysql/V1.6.0__add_uniqueness_module_record_user_id_module_id.sql
- src/main/resources/db/migration/mysql/V1.7.0__add-uid-column-in-module-record.sql
- src/test/java/uk/gov/cslearning/record/dto/factory/LearnerRecordEventFactoryTest.java
- src/test/java/uk/gov/cslearning/record/repository/ModuleRecordRepositoryTest.java
- src/test/java/uk/gov/cslearning/record/service/ModuleRecordServiceTest.java
- Added flyway script for enforcing uniqueness on the module_record table with module_id and user_id
> LC 1413 - add unique constraint for module_id and user_id on the module_record table

- src/main/java/uk/gov/cslearning/record/csrs/service/RegistryService.java
- src/main/java/uk/gov/cslearning/record/repository/CourseNotificationJobHistoryRepository.java
- src/main/java/uk/gov/cslearning/record/repository/CourseRecordRepository.java
- src/main/java/uk/gov/cslearning/record/service/NotifyService.java
- src/main/java/uk/gov/cslearning/record/service/scheduler/LearningJob.java
- src/main/java/uk/gov/cslearning/record/service/scheduler/Scheduler.java
- src/main/resources/application.yml
- src/test/java/uk/gov/cslearning/record/csrs/service/RegistryServiceTest.java
- src/test/java/uk/gov/cslearning/record/service/scheduler/LearningJobTest.java
- Remove the "Notify line manager of completed learning" job
> LC 3197 fix notifications

- src/main/java/uk/gov/cslearning/record/repository/ModuleRecordRepository.java
- src/main/java/uk/gov/cslearning/record/service/ModuleRecordService.java
- Add order by to Spring ORM queries
> LV-3532 Order by in Spring ORM

- src/main/java/uk/gov/cslearning/record/api/record/LearnerRecordEventQuery.java
- src/main/java/uk/gov/cslearning/record/repository/LearnerRecordEventRepository.java
- src/main/java/uk/gov/cslearning/record/service/LearnerRecordEventService.java
- src/main/java/uk/gov/cslearning/record/service/LearnerRecordService.java
- src/test/java/uk/gov/cslearning/record/integration/record/LearnerRecordEventTest.java
- add resourceID filter to GET events endpoint
> LC-3637 add resourceID filter to GET events endpoint
